version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    restart: always
    ports:
      - 8047:5432
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d

